### ISSUE TITLE
Running any example crashes

### ISSUE THREAD

**Issue by mosch** [sandyjmacdonald/keybow2040-circuitpython#14]
Hey there, thanks for providing the extensive docs to get started. 

I somehow run into an exception with using this lib. 

**I'm running (also tried with 7.0 & 7.1.0-rc.0)** 
```
Adafruit CircuitPython 7.1.0-beta.3 on 2021-12-13; Pimoroni Keybow 2040 with rp2040
Board ID:pimoroni_keybow2040
```

**The exception:**
```
code.py output:
Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "/lib/keybow2040.py", line 68, in __init__
  File "/lib/adafruit_is31fl3731/__init__.py", line 99, in __init__
  File "/lib/adafruit_is31fl3731/__init__.py", line 146, in _init
  File "/lib/adafruit_is31fl3731/__init__.py", line 169, in sleep
  File "/lib/adafruit_is31fl3731/__init__.py", line 135, in _register
  File "/lib/adafruit_is31fl3731/__init__.py", line 131, in _bank
  File "/lib/adafruit_is31fl3731/__init__.py", line 118, in _i2c_write_reg
AttributeError: 'PIM56X' object has no attribute 'try_lock'
```

I tried debugging by myself, but with limited success.  Any help much appreciated.

**Comment by mosch** [comment]
Got the hang of it. For future ref: Updated everything. Also examples and this lib to master. Works now.
